name: sos_docteur
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.1.4
  google_fonts: any
  flutter_svg: any
  date_picker_timeline: any
  page_transition: any
  flutter_rating_bar: any
  badges: any
  bubble_tab_indicator: "^0.1.5"
  scaled_list: ^1.0.1+6
  http: any
  image: ^3.0.8
  flutter_typeahead: ^3.2.1
  lottie: ^1.1.0
  flutter_spinkit: any
  get_storage: ^2.0.2
  expandable: ^5.0.1
  image_picker: any
  string_validator: ^0.3.0
  sqflite: ^1.1.3
  provider: ^5.0.0
  shimmer: ^2.0.0
  photo_view: ^0.13.0
  cloud_firestore: ^3.1.0
  firebase_storage: ^10.1.0
  permission_handler: any
  agora_rtc_engine: ^4.0.7
  firebase_core: ^1.10.0
  flutter_ringtone_player: any
  intl_phone_field: ^2.1.0
  flutter_launcher_icons: ^0.9.0
  connectivity: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/vector/
    - assets/images/shapes/
    - assets/images/doctors/
    - assets/lotties/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
